# Generated by Django 3.2.7 on 2021-10-10 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('number', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='number',
            name='duodigit',
        ),
        migrations.AddField(
            model_name='number',
            name='smallduodigit',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterField(
            model_name='number',
            name='numbers',
            field=models.CharField(max_length=8),
        ),
    ]
